a_list=[1,1,2,3,3]
a = tuple(a_list)
print(a)
b = list(a)
print(len(b))
c = set(b)
print(len(c))
d=list(c)
print(len(d))
e=list(range(1, 11, 1))
print(e)
dict = dict([(1,2),(3,4),(5,6),(7,8),(9,10)])
print(dict)
t= tuple(list(dict.items()))
print(t)
v = tuple(dict.keys())
print(v)
k = tuple(dict.values())
print(k)
s = "antidisestablishmentarianism"
print(s)
s = sorted(s)
print(s)
s2="".join(s)
print(s2)
w = "the quick brown fox jumped over the lazy dog"
w = w.split()
print(w)